2024-01-16T19:15:09.1896612 404 : [{"timestamp":"2024-01-17T00:15:09.136+00:00","status":404,"error":"Not Found","message":"No message available","path":"/1001/transferHistory"}]
2024-01-16T19:19:14.1538328 404 : [{"timestamp":"2024-01-17T00:19:14.008+00:00","status":404,"error":"Not Found","message":"No message available","path":"/1001/transferHistory"}]
2024-01-16T20:19:59.4981237 500 : [{"timestamp":"2024-01-17T01:17:43.643+00:00","status":500,"error":"Internal Server Error","message":"PreparedStatementCallback; bad SQL grammar [SELECT ts.transfer_status_desc FROM transfer_status ts JOIN transfer t USING(transfer_status_id) WHERE t.id=?]; nested exception is org.postgresql.util.PSQLException: ERROR: column t.id does not exist\n  Position: 104","path":"/1001/transferHistory"}]
2024-01-16T20:24:05.2743952 500 : [{"timestamp":"2024-01-17T01:24:05.237+00:00","status":500,"error":"Internal Server Error","message":"PreparedStatementCallback; bad SQL grammar [SELECT ts.transfer_status_desc FROM transfer_status ts JOIN transfer t USING(transfer_status_id) WHERE t.id=?]; nested exception is org.postgresql.util.PSQLException: ERROR: column t.id does not exist\n  Position: 104","path":"/1001/transferHistory"}]
2024-01-16T20:43:21.3677506 500 : [{"timestamp":"2024-01-17T01:43:21.299+00:00","status":500,"error":"Internal Server Error","message":"PreparedStatementCallback; bad SQL grammar [SELECT ts.transfer_status_desc FROM transfer_status ts JOIN transfer t USING(transfer_status_id) WHERE t.id=?]; nested exception is org.postgresql.util.PSQLException: ERROR: column t.id does not exist\n  Position: 104","path":"/1001/transferHistory"}]
2024-01-16T20:46:45.7000778 500 : [{"timestamp":"2024-01-17T01:46:45.634+00:00","status":500,"error":"Internal Server Error","message":"PreparedStatementCallback; bad SQL grammar [SELECT ts.transfer_status_desc FROM transfer_status ts JOIN transfer t USING(transfer_status_id) WHERE ts.id=?]; nested exception is org.postgresql.util.PSQLException: ERROR: column ts.id does not exist\n  Position: 104","path":"/1001/transferHistory"}]
2024-01-16T20:49:21.2216672 500 : [{"timestamp":"2024-01-17T01:49:21.180+00:00","status":500,"error":"Internal Server Error","message":"PreparedStatementCallback; bad SQL grammar [SELECT tt.transfer_type_desc FROM transfer_type tt JOIN transfer t USING(transfer_type_id) WHERE t.id=?]; nested exception is org.postgresql.util.PSQLException: ERROR: column t.id does not exist\n  Position: 98","path":"/1001/transferHistory"}]
2024-01-16T20:51:22.3353074 500 : [{"timestamp":"2024-01-17T01:51:22.285+00:00","status":500,"error":"Internal Server Error","message":"Cannot invoke \"com.techelevator.tenmo.model.User.getId()\" because the return value of \"com.techelevator.tenmo.dao.UserDao.getUserById(int)\" is null","path":"/1001/transferHistory"}]
2024-01-16T20:55:29.0937566 500 : [{"timestamp":"2024-01-17T01:55:29.030+00:00","status":500,"error":"Internal Server Error","message":"Cannot invoke \"com.techelevator.tenmo.model.User.getId()\" because the return value of \"com.techelevator.tenmo.dao.UserDao.getUserById(int)\" is null","path":"/1001/transferHistory"}]
